"""empty message

Revision ID: 7258d752253d
Revises: b62de4f84032
Create Date: 2017-04-24 14:45:29.224248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7258d752253d'
down_revision = 'b62de4f84032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'uname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('uname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
